spring.application.name=SpringBootApp
server.port=8083
spring.mvc.view.prefix=/
spring.mvc.view.suffix=.jsp
logging.level.org.springframework.web=DEBUG
# Automatically updates your database schema when you add new Java models
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL statements in the server logs (helpful for debugging)
spring.jpa.show-sql=true
